[0m14:18:51.092846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e25250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cbfd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cbf490>]}


============================== 14:18:51.095487 | 3bbcf070-84ff-4ff3-903b-1aade41d9cd5 ==============================
[0m14:18:51.095487 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:18:51.095937 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/christianrakotoarisoa/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init square_pipeline_project', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:18:51.104372 [debug] [MainThread]: Starter project path: /Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/include/starter_project
[0m14:18:51.109766 [info ] [MainThread]: 
Your new dbt project "square_pipeline_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:18:51.110120 [info ] [MainThread]: Setting up your profile.
[0m14:19:03.507398 [error] [MainThread]: Encountered an error:
list index out of range
[0m14:19:03.512239 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/christianrakotoarisoa/miniconda3/envs/we_eda/lib/python3.9/site-packages/dbt/task/init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m14:19:03.516118 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 12.469037, "process_in_blocks": "0", "process_kernel_time": 0.121444, "process_mem_max_rss": "96616448", "process_out_blocks": "0", "process_user_time": 0.632171}
[0m14:19:03.517321 [debug] [MainThread]: Command `dbt init` failed at 14:19:03.517129 after 12.47 seconds
[0m14:19:03.518106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e25250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d10cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cbfbb0>]}
[0m14:19:03.518890 [debug] [MainThread]: Flushing usage events
[0m14:19:03.895144 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:19:10.335285 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10390c2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10479ee50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10479e550>]}


============================== 14:19:10.337864 | 25f72d40-f1e7-42d1-87da-f76923e3981d ==============================
[0m14:19:10.337864 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:19:10.338305 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/christianrakotoarisoa/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init square_pipeline_project', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:19:10.344994 [info ] [MainThread]: A project called square_pipeline_project already exists here.
[0m14:19:10.346182 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.05178971, "process_in_blocks": "0", "process_kernel_time": 0.091544, "process_mem_max_rss": "96862208", "process_out_blocks": "0", "process_user_time": 0.626118}
[0m14:19:10.346619 [debug] [MainThread]: Command `dbt init` succeeded at 14:19:10.346554 after 0.05 seconds
[0m14:19:10.346875 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10390c2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10479ee50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10479e2e0>]}
[0m14:19:10.347112 [debug] [MainThread]: Flushing usage events
[0m14:19:10.460138 [debug] [MainThread]: An error was encountered while trying to flush usage events
